### ISSUE TITLE
Licensing Issues

### ISSUE THREAD

**Issue by lzcunt** [sorusclient/client#1]
All source code files in this repository are missing license headers. License headers are required because otherwise it isn't clear if the source is released under the LGPL-3.0-or-later or LGPL-3.0-only. There are two different headers I would suggest.

This first header style is recommended by the FSF:
```
This file is part of Sorus.

Sorus is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Sorusis distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License along with Sorus. If not, see <https://www.gnu.org/licenses/>.
```

The second option is using SPDX IDs, which is simpler:
```
// SPDX-License-Identifier: LGPL-3.0-or-later
```

Also, we should decide if Sorus contributors need to sign a CLA. Any licensing changes is better done in the early days of the project.

**Comment by danielcastelluccio** [comment]
I have made a few changes in the [license-reworks](https://github.com/sorusclient/client/tree/license-reworks) branch, both switching to MPL 2.0 and applying a header to [Sorus.kt](https://github.com/sorusclient/client/blob/license-reworks/src/main/kotlin/com/github/sorusclient/client/Sorus.kt). I would like your opinion on said changes before actual implementation.

**Comment by danielcastelluccio** [comment]
Closed bc I believe everything is fixed.
